[plugin]
previewers = [
  { name = "*/", run = "folder", sync = true },
  { name = "*.md", run = "preview" },
  { name = "*.csv", run = "preview" },
  { mime = "text/*", run = "code" },
  { mime = "*/xml", run = "code" },
  { mime = "*/javascript", run = "code" },
  { mime = "*/x-wine-extension-ini", run = "code" },
  { name = "*", run = "preview" },
]


[manager]
show_hidden = true
sort_by = "alphabetical"
sort_sensitive = false
sort_dir_first = true
sort_translit = true
show_symlink = true
scrolloff = 3

[preview]
tab_size = 1

