promptToReturnFromSubprocess: false
disableStartupPopups: true
quitOnTopLevelReturn: true
os:
  editPreset: "nvim"
gui:
  nerdFontsVersion: "3"
  skipNoStagedFilesWarning: false
  sidePanelWidth: 0.4
  expandFocusedSidePanel: false
  showFileTree: false
  showFileIcons: false
  showCommandLog: false
  showListFooter: false
  screenMode: half
  border: hidden

  showBottomLine: false
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  paging:
    colorArg: always
    pager: delta --dark --paging=never
